# Introduction to DAR

## What is Days in AR?

At its simplest, Days in AR is a mathematical formula that lets you work out how long your accounts receivable takes to clear. The easiest way to think of it is the number of days the average invoice will remain outstanding before payment is made. Completing your accounts receivable days formula gives you insight into how good your business, or your accounts receivables team, is at collecting payment on outstanding invoices.

The success of a practice's billing operations is often measured in AR days. The AR balance can be reduced by receiving payments or by entering contractual or write off adjustments. It is important to manage the A/R balance as claims become much more difficult to collect the older they become. Good management of the AR is also imperative to maintaining a good cash flow for the business. A poor AR process can result in loss of money to the business and result in financial strains to the owners. If all these tasks are being done properly, the days in A/R number should be low, in contrast, high days in AR number will most likely tell you there is a problem in your revenue cycle.

## What Does it Mean?

A growing number of Days in Accounts Receivable is symptomatic of a faulty billing process. For instance, let's say a practice has a **DAR** of *95 days*. This means that, on average, it takes the practice 95 days to collect it's outstanding balances. But what exactly does this mean? Is a **DAR** of 95 good? Is it bad? How bad or good is it?

### The Simple Answer

If you spend just a few minutes searching online, you'll come across as many different answers as links and pages you can click on. Many practices look to organizations such as MGMA[^intro-1] for industry-specific KPI standards or thresholds. Let's look at a couple of these. The table below is representative of a common scale for Days in AR you will come across when searching for benchmarking standards:

[^intro-1]: <https://www.mgma.com/>

<br>

```{r benchex, echo=FALSE, fig.cap="A common DAR scale for benchmarking.", message=FALSE, warning=FALSE}
require(gt)
dar_kpi_ex <- read.csv("data/dar_kpi_ex.csv") %>% janitor::clean_names()
dar_kpi_ex %>% 
    gt() %>% 
    cols_label("i_days_in_ar" = md("**Days in Accounts Receivable**"),
               `performance` = md("**Performance**")) %>%
    opt_row_striping(row_striping = TRUE)
```

<br>

Two more common "rules of thumb" that I've come across are:<br>

> *As a general rule, you'll want to aim for around **25%** longer than the payment date on your stated payment terms.*

> *It is understood that your monthly **Ending Accounts Receivable Balance** should never be more than **1.5 times** your **total Gross Monthly Charges**.*

<br>

We'll further explore these last two pieces of general advice later, but the point of my highlighting these "easy" answers is that they are, in fact, excellent *general* answers. However, each medical practice is a unique animal, made up of a complex web of distinct attributes. Benchmarking standards, however well-meaning they intend to be, apply to the average of *all* medical practices surveyed by the organization that publishes them.

### The Complex Answer

Let's go back to the **DAR** of *95 days* and what it means for the practice from the example. The immediate insight is that it takes, on average, 95 days for this practice to collect it's unpaid balances. The deeper insight is that at least three months of working capital is required to maintain the practice's cash flow needs. 95 days is roughly equal to three months, thus, there's three months of unpaid work sitting in Accounts Receivable. Therefore, if the practice is going to meet its financial obligations (i.e., payroll, rent, etc.), it's going to need three months of cash reserves available, or it will have to borrow these amounts, which will in turn have additional repercussions.

The "ideal" average Days in AR depends entirely upon the medical practice, its customers (patients), and its customers' payers, whether they be third-party payers or the patient themselves. It also depends on the services it supplies and the providers performing those services. Finally, it will depend on the financial situation of the practice and its stakeholders.

A practice's DAR number can have different meanings across different types of practices as well. Having a very high DAR number can be indicative of a too-lenient policy with late-paying customers, or it could simply be standard for your specialty. On the other hand, having a very low DAR number could indicate a great working relationship with your patients, or that you have a hard-line approach to your payment policy that is alienating longtime patients and potentially cutting off new business.

### A Starting Point for Further Analysis

I say all of that to say this: Judging the financial health of your medical practice by comparing it's performance to industry-standard benchmarks is akin to someone telling you that the best way to see if your house is still standing after a terrible storm is to take a look at it while standing on the moon. *"See? It's that dot right there, everything's fine."*

What if you could just drive to your house, walk around inside, and inspect the contents of each room? My proposal is a very simple one: familiarize yourself with the pieces that make up the DAR metric and you will be much better informed about not only Days in AR, but almost every other significant KPI, as Days in AR connects to each of them in some way, great and small.

The purpose of a good KPI (or group of KPIs) is to reduce the amount of time and cognitive load it requires to understand a large, complex set of data that is constantly being added to. The problem that many people run into is a lack of understanding of the basic foundations of these metrics and their fundamental inter-connectivity. Monitors of the KPIs cannot then use them to properly anticipate and prevent the problems that they're meant to highlight.

## Essential Meaning of the Calculation

The core idea of the calculation to determine **DAR** is to go through each individual claim, count the days from the **Date of Service** to the **Date of (full) Payment**, add all of those up, and divide by the total number of claims. This is an extremely laborious process, so other formulas have taken it's place. The most commonly used is as follows:

-   Divide the **total Gross Charges** by the **Number of Days** in the period that you are measuring. This is the **Average Daily Charge** for that period.

-   Divide the **Ending AR Balance** for the same period by the **Average Daily Charge**. This is the average **Days in AR** for that period.

### Gross Charges as Opposed to Net Charges?

This is a great question and one that we'll explore in more detail when we discuss the Revenue Cycle workflow. The short answer is that Net Charges excludes such things as contractual adjustments, and so it's missing important information. Within the space of two numbers, AR Balance and Gross Charges, you can tell the story of an organization's financial history. This idea of representing comes from the world of accounting and I find it brilliant in it's simplicity.

To account is to bear witness. As the financial historian of a business entity, the accountant must be able to explain in the simplest terms possible, the financial events, past and present. So, there is a restriction involved, called a *monetary denominator*. Even if no reimbursement is involved, an event is described in terms of amounts of currency, rather than exhaustively describing the banal minutiae of each paper clip purchase. This number can be investigated extensively if the stakeholders see fit. And why wouldn't they? It contains the entirety of the company's financial history.

In much the same spirit, the Gross Charge figure contains the total account of work done while the Ending AR Balance is the exhaustive archive of compensation and recompense on behalf of that work.

## Advantages & Disadvantages

A few more words on what the DAR metric is and is not. Again, it would not be appropriate to compare the DAR of medical practices with different specialties. For example, a cardiology group's DAR would not compare to a plastic surgery practice's DAR because the methods of reimbursement for these two entities are entirely different. Not only does the DAR metric depend on medical specialty, but also patient demographics, payer mix, and procedure sample.

Another disadvantage is that it is sensitive to the provider because it counts the lag time of unsubmitted claims for services already delivered. However, this lag time roughly averages across all payers, making DAR an effective comparison between payers for an individual provider, but invalidating it across multiple providers. One obvious advantage of the DAR metric is its independence of charges. The average feature of this metric eliminates sensitivity to a specific day or CPT, but it also hides the behavior shape of the AR curve.

To make up for these weaknesses, there are adjusted formulas as well as other metrics (such as **PARBX**[^intro-2]) that we'll use to fill in these gaps.

[^intro-2]: Percentage of AR Beyond $x$ Days
